---
- name: install the INDIGO release package
  apt:
    name: python-cloud-info-provider-indigo
    state: latest
    deb: http://jenkins.indigo-datacloud.eu/repository/indigo-testing/1/ubuntu/dists/trusty/main/binary-amd64/indigodc-release_1.0.0-1_amd64.deb

- name: Install cloud-info-provider
  apt:
    name: python-cloud-info-provider-indigo
    state: latest
    update_cache: yes
