---
# XXX install before repo as repo's version has broken dependencies
- name: Install python-novaclient
  apt:
    name: python-novaclient
    state: latest
  when: cloud_info_provider_middleware == 'openstack'

- name: Install the INDIGO GPG key
  apt_key:
    state: present
    url: http://repo.indigo-datacloud.eu/repository/RPM-GPG-KEY-indigodc

- name: install the INDIGO release package
  apt:
    state: present
    deb: http://jenkins.indigo-datacloud.eu/repository/indigo/1/ubuntu/dists/trusty/main/binary-amd64/indigodc-release_1.0.0-1_amd64.deb

- name: Install cloud-info-provider
  apt:
    name: python-cloud-info-provider-indigo
    state: latest
    update_cache: yes
