---
- name: Exit if OS is unsupporeted
  fail:
    msg="Role unsupported on {{ansible_distribution}}"
  when: "ansible_os_family != 'Debian' and ansible_os_family != 'RedHat'"

- include_vars: defaults/main.yml

- name: Load debian-specific configuration
  include debian.yml
  when ansible_distribution == 'Debian'

- name: Load RHEL-specific configuration
  include rhel.yml
  when ansible_distribution == 'RedHat'

- name: Configure cloud-info-provider
  template: src=main_conf.j2 dest={{ cloud_info_provider_conf_dir }}/{{ cloud_info_provider_main_conf_file }}
