---
- name: Install the INDIGO GPG key
  rpm_key:
    state: present
    key: http://repo.indigo-datacloud.eu/repository/RPM-GPG-KEY-indigodc

- name: install the INDIGO release package
  yum:
    name: http://jenkins.indigo-datacloud.eu/repository/indigo/1/centos7/x86_64/base/indigodc-release-1.0.0-1.el7.centos.noarch.rpm
    state: present

- name: Install cloud-info-provider
  yum:
    name: cloud-info-provider-indigo
    state: latest
    update_cache: yes

- name: Install python-novaclient
  yum:
    name: python-novaclient
    state: latest
  when: cloud_info_provider_middleware == 'openstack'
